# Generated by Django 4.2.11 on 2024-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cashcall',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='fees_type',
            field=models.CharField(choices=[('Upfront', 'Upfront'), ('Yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='fees_type',
            field=models.CharField(choices=[('Upfront', 'Upfront'), ('Yearly', 'Yearly')], max_length=10),
        ),
    ]
